package com.snapIT.morningChallenges.week6;

// Each new term in the Fibonacci sequence is generated by adding the previous two terms.
// By starting with 1 and 2, the first 10 terms will be:
//
//        0,1,1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ... = 10 even valued terms

// By considering the terms in the Fibonacci
// sequence whose values do not exceed four million,
// find the sum of the even-valued terms.

// take values up to four million
// create variables to take the value of a previous number
// create a variable to take the value of the previous previous #

// lets print the fibonacci sequence



public class fibonacciSum {
    public static void main(String[] args) {

        System.out.println(fibonnacciSum(4000000));
    }

    public static double fibonnacciSum(double upTo) {

        int firstPrevious = 1;
        int nextPrevious = 0;
        int fiboNumber = firstPrevious + nextPrevious;
        int sum = 0;

        for(int i = 0; fiboNumber <= upTo; i++ ) {
//            System.out.println( fiboNumber);
            nextPrevious = firstPrevious;
            firstPrevious = fiboNumber;
            fiboNumber = firstPrevious + nextPrevious;

            if(fiboNumber % 2 == 0) {
                sum += fiboNumber;
            }
        }

        return sum;
    }

}
